### PR TITLE
Move x5c into key and added required parameters

### PR DESCRIPTION
**Pull request by OmegaPointZero**
* Moved the x509 Certificate into the key
* Added the fields for `use`, `expires_on` and `alg` per Chase's requirements

### CODE REVIEW

**Review by mhanberry — CHANGES_REQUESTED** [review]
Don't change all the tabs to spaces. If this PR were larger, your changes would be unreadable.

**Comment by OmegaPointZero** [comment]
Sorry, I didn't even notice, it's just a setting on the text editor to keep all of our python and Larky stuff from breaking. But I don't understand how this is now somehow unreadable?

**Comment by mhanberry** [comment]
It's not a big deal. I was just saying that if this were a larger PR, then it would be difficult to tell what you had changed in a meaningful way.

I didn't want to make you re-write your code, so I took care of it here:
https://github.com/mhanberry/pem-to-jwk/pull/2

consolidated lines 10-14 too

**Comment by OmegaPointZero** [comment]
Ah, okay, I see what you're saying. I think all of that might've been highlighted anyway, as it still was after I fixed the tabbing. Cool 👍 Thanks!

**Pull request closed without merging**
